In [10]:
import pandas as pd
import numpy as np

In [11]:

test=pd.read_csv(r"C:\Users\kinsh\Downloads\0000000000002417_test_boston_x_test.csv",delimiter=',')

In [12]:
test=pd.DataFrame(test)
test=test.values

In [37]:
test
x_test=test

In [14]:
train=pd.read_csv(r"C:\Users\kinsh\Downloads\0000000000002417_training_boston_x_y_train.csv",delimiter=',')
y_train=train.iloc[:,13]
y_train=y_train.values
y_train

array([37.9, 21.4, 12.7, 19.9, 22.5, 32.7, 23.2, 21.5, 20.5, 33.3, 23.1,
       20. , 50. , 25. , 20.2, 16.4, 22.4, 20.4, 18.4, 37.3, 23.1, 34.7,
       33.1, 28.7, 15.6, 18.2, 17.2, 31.5, 26.6, 24.1, 22.3, 19.5, 36.1,
       17.6, 33.4,  8.8,  9.7, 13.4, 39.8, 24.4, 17.8, 24.3, 24. , 23.1,
       13.1, 16.7, 22.8, 27.5, 14.6, 13.4, 11. , 19.4, 15. , 44.8, 29.6,
       12.3, 24.6, 10.9, 28. , 30.8, 15.4, 18. , 35.2, 11.5, 19.5, 24.8,
       22.2, 20.1, 15.2, 50. , 17.1, 23. , 12. , 22. , 20. , 20.3, 17.2,
       37.2,  5. , 24.5, 18.9, 24.5, 24.8, 21.6,  7. , 17.7, 12.8, 14.9,
       18.3, 15.6, 19.9, 22.2, 16.7, 32.5, 25.1, 30.1, 16.1, 20.7, 46. ,
       22.3, 23. , 11.9, 23.3, 23.2, 22. , 10.5, 17.2, 29.8, 29. , 17.3,
       20.6, 20.1, 20.6, 17.8, 25. , 22.6, 18.7, 11.3,  9.6, 17.8, 23.9,
       38.7, 21.2, 25. , 28.5, 24. , 20.6,  5. , 22.9, 18.4, 31. , 36. ,
       20.8, 13.3, 23.2, 28.2, 43.8, 26.6, 23.9, 23.9, 27.9, 19.1, 30.5,
        8.3,  8.5, 16.5, 23.8, 19.6, 22.2, 24.3, 32

In [15]:


train=pd.DataFrame(train)
train=train.values
train=train[:,0:13]
train
x_train=train

In [16]:
x_train

array([[-0.40784991, -0.48772236, -1.2660231 , ..., -0.30309415,
         0.41057102, -1.09799011],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.29116915, -0.52047412],
       [ 0.1251786 , -0.48772236,  1.01599907, ...,  0.80657583,
        -3.79579542,  0.89107588],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.33206621, -0.33404299],
       [-0.41061997, -0.48772236, -1.15221381, ..., -0.71922039,
         0.203235  , -0.74475218],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.80657583,
         0.38787479, -1.35871335]])

In [17]:
y_train

array([37.9, 21.4, 12.7, 19.9, 22.5, 32.7, 23.2, 21.5, 20.5, 33.3, 23.1,
       20. , 50. , 25. , 20.2, 16.4, 22.4, 20.4, 18.4, 37.3, 23.1, 34.7,
       33.1, 28.7, 15.6, 18.2, 17.2, 31.5, 26.6, 24.1, 22.3, 19.5, 36.1,
       17.6, 33.4,  8.8,  9.7, 13.4, 39.8, 24.4, 17.8, 24.3, 24. , 23.1,
       13.1, 16.7, 22.8, 27.5, 14.6, 13.4, 11. , 19.4, 15. , 44.8, 29.6,
       12.3, 24.6, 10.9, 28. , 30.8, 15.4, 18. , 35.2, 11.5, 19.5, 24.8,
       22.2, 20.1, 15.2, 50. , 17.1, 23. , 12. , 22. , 20. , 20.3, 17.2,
       37.2,  5. , 24.5, 18.9, 24.5, 24.8, 21.6,  7. , 17.7, 12.8, 14.9,
       18.3, 15.6, 19.9, 22.2, 16.7, 32.5, 25.1, 30.1, 16.1, 20.7, 46. ,
       22.3, 23. , 11.9, 23.3, 23.2, 22. , 10.5, 17.2, 29.8, 29. , 17.3,
       20.6, 20.1, 20.6, 17.8, 25. , 22.6, 18.7, 11.3,  9.6, 17.8, 23.9,
       38.7, 21.2, 25. , 28.5, 24. , 20.6,  5. , 22.9, 18.4, 31. , 36. ,
       20.8, 13.3, 23.2, 28.2, 43.8, 26.6, 23.9, 23.9, 27.9, 19.1, 30.5,
        8.3,  8.5, 16.5, 23.8, 19.6, 22.2, 24.3, 32

In [67]:
x_test=test
x_test

array([[-0.40339151, -0.48772236,  0.40609801, ..., -1.13534664,
         0.44105193, -0.89473812],
       [-0.4131781 , -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.50084979],
       [-0.41264948,  0.41358857, -0.80203138, ..., -0.76545664,
         0.44105193, -0.59196275],
       ...,
       [-0.41001449,  2.08745172, -1.37837329, ..., -0.0719129 ,
         0.39094481, -0.68167397],
       [-0.40317611, -0.48772236, -0.37597609, ...,  1.13022958,
         0.34007019,  0.20142086],
       [-0.13356344, -0.48772236,  1.2319449 , ..., -1.73641788,
        -2.93893082,  0.48877712]])

In [52]:
def step_gradient(x_train,y_train,learning_rate, m , c):
    m_slope = np.zeros(13)
    c_slope = 0
    M = len(x_train)
    for i in range(M):
        for j in range(13):
            m_slope[j] += (-2/M)* (y_train[i] - m[j] * x_train[i][j] - c)*x_train[i][j]
            c_slope += (-2/M)* (y_train[i] - m[j] * x_train[i][j] - c)
    new_m = m - learning_rate * m_slope
    new_c = c - learning_rate * c_slope
    print(cost(x_train,y_train,new_m,new_c))
    return new_m, new_c

In [57]:
def cost(x_train,y_train,new_m,new_c):
    M=len(x_train)
    total_cost=0
    for i in range(len(x_train)):
        total_cost=total_cost+(y_train[i]-(new_m*x_train[i]).sum()-new_c)**2
    return total_cost/M
        

In [58]:
def gd(x_train,y_train, learning_rate, num_iterations):
    m = np.zeros(13)       
    c = 0       
    for i in range(num_iterations):
        m, c = step_gradient(x_train,y_train, learning_rate, m , c)
        #print(i, " Cost: ", cost(points, m, c))
    return m, c

In [102]:
def run():
    learning_rate = 0.01
    num_iterations = 10
    m, c = gd(x_train,y_train, learning_rate, num_iterations)
    print("Final m :", m)
    print("Final c :", c)
    return m,c

In [103]:
m,c=run()

360.23985038817705
226.57185139147958
150.90329628028823
107.38596103807517
81.86137050729678
66.56569609262937
57.23283340648733
51.50981442471678
48.09024241562486
46.24050566144874
Final m : [-0.63882351  0.54399633 -0.7891224   0.3527052  -0.67317521  1.20110149
 -0.5488871   0.40750402 -0.55107759 -0.71626286 -0.8200511   0.5496904
 -1.26494808]
Final c : 21.50270963985036


In [104]:
def predictOne(x_test_one,m,c):
    return (x_test_one*m).sum()+c



In [105]:
y_pred=[]
for i in range(len(x_test)):
    y_pred.append(predictOne(x_test[i],m,c))

In [106]:
y_pred=np.array(y_pred)
y_pred.shape

(126,)

In [107]:
y_pred

array([26.75101749, 21.5032359 , 26.88957127, 21.45006878, 11.98414272,
       26.23236463, 24.13590993, 21.09224802, 23.62090847, 25.07806886,
       20.70477403, 24.65891081, 22.8039742 , 27.76801405, 26.95147805,
       25.2329672 , 25.02575065, 25.67048755, 26.31949202, 21.80623212,
       20.23968546, 23.45015053, 29.65202959, 31.5623974 , 13.91054377,
       21.98398717, 28.56365619, 22.20059976, 25.85024056, 20.76278745,
       24.69298294, 22.36247747, 24.93132204, 12.94078883, 24.52071378,
       26.49222545, 20.61465663, 26.08330477, 10.23496108,  9.17903664,
       27.41255541, 30.11270578, 18.55134912, 16.68032249,  7.80231661,
       28.45668776, 23.31533017, 31.94495243, 14.40522034, 14.14200158,
       33.37902767, 14.57436712, 20.78068036, 20.19445772, 23.62618286,
       21.19535638, 23.75401244, 19.2210768 , 14.53463678, 11.3285067 ,
       24.30875604, 24.35944616, 24.90363643, 14.11286641, 13.37142524,
       26.84227694, 14.29084184, 23.63584397, 18.4660155 , 26.00

In [108]:
np.savetxt("D:\BostonPredictions.csv", y_pred, delimiter=",",fmt='%1.15f')

In [109]:
from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor()
model.fit(x_train,y_train)

GradientBoostingRegressor()

In [110]:
y_pred1=model.predict(x_test)
y_pred1

array([26.80499145, 17.09852907, 22.06512279, 21.19058003, 12.2832724 ,
       28.22068484, 25.20237061, 18.77275134, 22.99272373, 23.39058111,
       17.6291958 , 19.64676654, 20.8280366 , 51.86380438, 21.03836143,
       23.49131107, 22.87310447, 19.17816831, 30.68495565, 20.89789526,
       21.49588187, 36.62299579, 31.39775722, 33.55395804, 16.38574194,
       20.47642029, 30.64770333, 19.97381035, 28.7847961 , 17.218498  ,
       24.68879147, 20.79190642, 22.83448526,  8.58056865, 23.80896034,
       22.57697789, 20.44057093, 22.71189925,  8.0482711 , 14.94221917,
       23.59244202, 25.06137752, 19.90148152, 21.80376912, 10.01740755,
       43.705159  , 24.57774682, 34.20275194, 12.83411894, 14.06393226,
       45.23318763, 14.38762866, 20.95608777, 16.3818815 , 19.69745011,
       18.88744499, 22.4778254 , 15.32494152, 15.84899874, 13.68437009,
       27.27249687, 22.29881719, 23.0038954 , 14.49435547, 16.20543174,
       32.88520177, 12.57183546, 20.91664926, 21.38865206, 26.89

In [111]:
y_pred

array([26.75101749, 21.5032359 , 26.88957127, 21.45006878, 11.98414272,
       26.23236463, 24.13590993, 21.09224802, 23.62090847, 25.07806886,
       20.70477403, 24.65891081, 22.8039742 , 27.76801405, 26.95147805,
       25.2329672 , 25.02575065, 25.67048755, 26.31949202, 21.80623212,
       20.23968546, 23.45015053, 29.65202959, 31.5623974 , 13.91054377,
       21.98398717, 28.56365619, 22.20059976, 25.85024056, 20.76278745,
       24.69298294, 22.36247747, 24.93132204, 12.94078883, 24.52071378,
       26.49222545, 20.61465663, 26.08330477, 10.23496108,  9.17903664,
       27.41255541, 30.11270578, 18.55134912, 16.68032249,  7.80231661,
       28.45668776, 23.31533017, 31.94495243, 14.40522034, 14.14200158,
       33.37902767, 14.57436712, 20.78068036, 20.19445772, 23.62618286,
       21.19535638, 23.75401244, 19.2210768 , 14.53463678, 11.3285067 ,
       24.30875604, 24.35944616, 24.90363643, 14.11286641, 13.37142524,
       26.84227694, 14.29084184, 23.63584397, 18.4660155 , 26.00

In [118]:
from sklearn.metrics import mean_absolute_error
mse_classifier = mean_absolute_error(y_pred1,y_pred)
print(mse_classifier)

3.191136930738959


In [119]:
np.savetxt("D:\BostonPredictions1.csv", y_pred1, delimiter=",",fmt='%1.15f')