In [59]:
import numpy as np
import pandas as pd
from sklearn import model_selection
training=pd.read_csv(r"D:\0000000000002429_training_titanic_x_y_train.csv",delimiter=',')
testing=pd.read_csv(r"D:\0000000000002429_test_titanic_x_test.csv",delimiter=',')
training


Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
663       2                             Ilett, Miss. Bertha  female  17.0   
664       3                        Morrow, Mr. Thomas Rowan    male   NaN   
665       3                                   Bing, Mr. Lee    male  32.0   
666       3                     Strandberg, Miss. Ida Sofia  female  22.0   
667       3                  Murphy, Miss. Katherine "Kate"  female   NaN   

     SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0        1      0           228414  26.0000   NaN        S         1  
1        0      0         A/5 2466   8.0500   NaN        S         0  
2        0      0           250655  26.0000   NaN        S         0  
3        0      4           349909  21.0750   NaN        S         0  
4        0      0  SOTON/OQ 392076   7.0500   NaN        S         0  
..     ...    ...              ...      ...   ...      ...       ...  
663      0      0       SO/C 14885  10.5000   NaN        S         1  
664      0      0           372622   7.7500   NaN        Q         0  
665      0      0             1601  56.4958   NaN        S         1  
666      0      0             7553   9.8375   NaN        S         0  
667      1      0           367230  15.5000   NaN        Q         1  

[668 rows x 11 columns]

In [60]:
training['Ticket'].value_counts()

1601                6
347082              6
3101295             6
CA. 2343            5
S.O.C. 14879        5
                   ..
368323              1
364512              1
347466              1
STON/O2. 3101271    1
367230              1
Name: Ticket, Length: 524, dtype: int64

In [61]:
training.describe(include='all')

Pclass                                           Name   Sex  \
count   668.000000                                            668   668   
unique         NaN                                            668     2   
top            NaN  Weisz, Mrs. Leopold (Mathilde Francoise Pede)  male   
freq           NaN                                              1   427   
mean      2.296407                                            NaN   NaN   
std       0.831638                                            NaN   NaN   
min       1.000000                                            NaN   NaN   
25%       2.000000                                            NaN   NaN   
50%       3.000000                                            NaN   NaN   
75%       3.000000                                            NaN   NaN   
max       3.000000                                            NaN   NaN   

               Age       SibSp       Parch Ticket        Fare Cabin Embarked  \
count   536.000000  668.000000  668.000000    668  668.000000   154      667   
unique         NaN         NaN         NaN    524         NaN   119        3   
top            NaN         NaN         NaN   1601         NaN    G6        S   
freq           NaN         NaN         NaN      6         NaN     4      484   
mean     29.700560    0.528443    0.407186    NaN   32.064552   NaN      NaN   
std      14.240257    1.080327    0.854695    NaN   45.320835   NaN      NaN   
min       0.670000    0.000000    0.000000    NaN    0.000000   NaN      NaN   
25%      21.000000    0.000000    0.000000    NaN    7.925000   NaN      NaN   
50%      29.000000    0.000000    0.000000    NaN   14.750000   NaN      NaN   
75%      38.250000    1.000000    0.000000    NaN   31.275000   NaN      NaN   
max      80.000000    8.000000    6.000000    NaN  512.329200   NaN      NaN   

          Survived  
count   668.000000  
unique         NaN  
top            NaN  
freq           NaN  
mean      0.402695  
std       0.490808  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000

In [62]:
training.describe()

Pclass         Age       SibSp       Parch        Fare    Survived
count  668.000000  536.000000  668.000000  668.000000  668.000000  668.000000
mean     2.296407   29.700560    0.528443    0.407186   32.064552    0.402695
std      0.831638   14.240257    1.080327    0.854695   45.320835    0.490808
min      1.000000    0.670000    0.000000    0.000000    0.000000    0.000000
25%      2.000000   21.000000    0.000000    0.000000    7.925000    0.000000
50%      3.000000   29.000000    0.000000    0.000000   14.750000    0.000000
75%      3.000000   38.250000    1.000000    0.000000   31.275000    1.000000
max      3.000000   80.000000    8.000000    6.000000  512.329200    1.000000

In [63]:
training.describe

<bound method NDFrame.describe of      Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
663       2                             Ilett, Miss. Bertha  female  17.0   
664       3                        Morrow, Mr. Thomas Rowan    male   NaN   
665       3                                   Bing, Mr. Lee    male  32.0   
666       3                     Strandberg, Miss. Ida Sofia  female  22.0   
667       3                  Murphy, Miss. Katherine "Kate"  female   NaN   

     SibSp  Parch           Ticket     Fa

In [64]:
training.describe(include='all')

Pclass                                           Name   Sex  \
count   668.000000                                            668   668   
unique         NaN                                            668     2   
top            NaN  Weisz, Mrs. Leopold (Mathilde Francoise Pede)  male   
freq           NaN                                              1   427   
mean      2.296407                                            NaN   NaN   
std       0.831638                                            NaN   NaN   
min       1.000000                                            NaN   NaN   
25%       2.000000                                            NaN   NaN   
50%       3.000000                                            NaN   NaN   
75%       3.000000                                            NaN   NaN   
max       3.000000                                            NaN   NaN   

               Age       SibSp       Parch Ticket        Fare Cabin Embarked  \
count   536.000000  668.000000  668.000000    668  668.000000   154      667   
unique         NaN         NaN         NaN    524         NaN   119        3   
top            NaN         NaN         NaN   1601         NaN    G6        S   
freq           NaN         NaN         NaN      6         NaN     4      484   
mean     29.700560    0.528443    0.407186    NaN   32.064552   NaN      NaN   
std      14.240257    1.080327    0.854695    NaN   45.320835   NaN      NaN   
min       0.670000    0.000000    0.000000    NaN    0.000000   NaN      NaN   
25%      21.000000    0.000000    0.000000    NaN    7.925000   NaN      NaN   
50%      29.000000    0.000000    0.000000    NaN   14.750000   NaN      NaN   
75%      38.250000    1.000000    0.000000    NaN   31.275000   NaN      NaN   
max      80.000000    8.000000    6.000000    NaN  512.329200   NaN      NaN   

          Survived  
count   668.000000  
unique         NaN  
top            NaN  
freq           NaN  
mean      0.402695  
std       0.490808  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000

In [65]:
tr=training

In [66]:
tr

Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
663       2                             Ilett, Miss. Bertha  female  17.0   
664       3                        Morrow, Mr. Thomas Rowan    male   NaN   
665       3                                   Bing, Mr. Lee    male  32.0   
666       3                     Strandberg, Miss. Ida Sofia  female  22.0   
667       3                  Murphy, Miss. Katherine "Kate"  female   NaN   

     SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0        1      0           228414  26.0000   NaN        S         1  
1        0      0         A/5 2466   8.0500   NaN        S         0  
2        0      0           250655  26.0000   NaN        S         0  
3        0      4           349909  21.0750   NaN        S         0  
4        0      0  SOTON/OQ 392076   7.0500   NaN        S         0  
..     ...    ...              ...      ...   ...      ...       ...  
663      0      0       SO/C 14885  10.5000   NaN        S         1  
664      0      0           372622   7.7500   NaN        Q         0  
665      0      0             1601  56.4958   NaN        S         1  
666      0      0             7553   9.8375   NaN        S         0  
667      1      0           367230  15.5000   NaN        Q         1  

[668 rows x 11 columns]

In [67]:
tr=tr.drop('Name',axis=1)

In [68]:
tr

Pclass     Sex   Age  SibSp  Parch           Ticket     Fare Cabin  \
0         2  female  29.0      1      0           228414  26.0000   NaN   
1         3    male   NaN      0      0         A/5 2466   8.0500   NaN   
2         2    male  39.0      0      0           250655  26.0000   NaN   
3         3  female  29.0      0      4           349909  21.0750   NaN   
4         3    male  25.0      0      0  SOTON/OQ 392076   7.0500   NaN   
..      ...     ...   ...    ...    ...              ...      ...   ...   
663       2  female  17.0      0      0       SO/C 14885  10.5000   NaN   
664       3    male   NaN      0      0           372622   7.7500   NaN   
665       3    male  32.0      0      0             1601  56.4958   NaN   
666       3  female  22.0      0      0             7553   9.8375   NaN   
667       3  female   NaN      1      0           367230  15.5000   NaN   

    Embarked  Survived  
0          S         1  
1          S         0  
2          S         0  
3          S         0  
4          S         0  
..       ...       ...  
663        S         1  
664        Q         0  
665        S         1  
666        S         0  
667        Q         1  

[668 rows x 10 columns]

This gives all the rows with 'Sex' column=='female'

In [69]:
tr.loc[tr['Sex']=='female']

Pclass     Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  \
0         2  female  29.0      1      0      228414  26.0000   NaN        S   
3         3  female  29.0      0      4      349909  21.0750   NaN        S   
6         1  female  35.0      1      0      113803  53.1000  C123        S   
10        3  female  23.0      0      0    CA. 2314   7.5500   NaN        S   
14        3  female   NaN      0      0      370375   7.7500   NaN        Q   
..      ...     ...   ...    ...    ...         ...      ...   ...      ...   
658       3  female  38.0      1      5      347077  31.3875   NaN        S   
661       1  female   NaN      1      0    PC 17604  82.1708   NaN        C   
663       2  female  17.0      0      0  SO/C 14885  10.5000   NaN        S   
666       3  female  22.0      0      0        7553   9.8375   NaN        S   
667       3  female   NaN      1      0      367230  15.5000   NaN        Q   

     Survived  
0           1  
3           0  
6           1  
10          1  
14          1  
..        ...  
658         1  
661         1  
663         1  
666         0  
667         1  

[241 rows x 10 columns]

In [70]:
tq=tr.copy()
tq.loc[tr['Sex']=='female']=0


tq.loc[tr['Sex']=='female']=0 this makes all attributes zero only in the female rows

In [71]:
tq

Pclass   Sex   Age  SibSp  Parch           Ticket     Fare Cabin  \
0         0     0   0.0      0      0                0   0.0000     0   
1         3  male   NaN      0      0         A/5 2466   8.0500   NaN   
2         2  male  39.0      0      0           250655  26.0000   NaN   
3         0     0   0.0      0      0                0   0.0000     0   
4         3  male  25.0      0      0  SOTON/OQ 392076   7.0500   NaN   
..      ...   ...   ...    ...    ...              ...      ...   ...   
663       0     0   0.0      0      0                0   0.0000     0   
664       3  male   NaN      0      0           372622   7.7500   NaN   
665       3  male  32.0      0      0             1601  56.4958   NaN   
666       0     0   0.0      0      0                0   0.0000     0   
667       0     0   0.0      0      0                0   0.0000     0   

    Embarked  Survived  
0          0         0  
1          S         0  
2          S         0  
3          0         0  
4          S         0  
..       ...       ...  
663        0         0  
664        Q         0  
665        S         1  
666        0         0  
667        0         0  

[668 rows x 10 columns]

In [72]:
tr.loc[tr['Sex']=='female','Sex']=0

Only the 'Sex' column is made 0, female is replaced by 0.

In [73]:
tr

Pclass   Sex   Age  SibSp  Parch           Ticket     Fare Cabin  \
0         2     0  29.0      1      0           228414  26.0000   NaN   
1         3  male   NaN      0      0         A/5 2466   8.0500   NaN   
2         2  male  39.0      0      0           250655  26.0000   NaN   
3         3     0  29.0      0      4           349909  21.0750   NaN   
4         3  male  25.0      0      0  SOTON/OQ 392076   7.0500   NaN   
..      ...   ...   ...    ...    ...              ...      ...   ...   
663       2     0  17.0      0      0       SO/C 14885  10.5000   NaN   
664       3  male   NaN      0      0           372622   7.7500   NaN   
665       3  male  32.0      0      0             1601  56.4958   NaN   
666       3     0  22.0      0      0             7553   9.8375   NaN   
667       3     0   NaN      1      0           367230  15.5000   NaN   

    Embarked  Survived  
0          S         1  
1          S         0  
2          S         0  
3          S         0  
4          S         0  
..       ...       ...  
663        S         1  
664        Q         0  
665        S         1  
666        S         0  
667        Q         1  

[668 rows x 10 columns]

In [74]:
tr.loc[tr['Sex']=='male','Sex']=1

In [75]:
tr

Pclass Sex   Age  SibSp  Parch           Ticket     Fare Cabin Embarked  \
0         2   0  29.0      1      0           228414  26.0000   NaN        S   
1         3   1   NaN      0      0         A/5 2466   8.0500   NaN        S   
2         2   1  39.0      0      0           250655  26.0000   NaN        S   
3         3   0  29.0      0      4           349909  21.0750   NaN        S   
4         3   1  25.0      0      0  SOTON/OQ 392076   7.0500   NaN        S   
..      ...  ..   ...    ...    ...              ...      ...   ...      ...   
663       2   0  17.0      0      0       SO/C 14885  10.5000   NaN        S   
664       3   1   NaN      0      0           372622   7.7500   NaN        Q   
665       3   1  32.0      0      0             1601  56.4958   NaN        S   
666       3   0  22.0      0      0             7553   9.8375   NaN        S   
667       3   0   NaN      1      0           367230  15.5000   NaN        Q   

     Survived  
0           1  
1           0  
2           0  
3           0  
4           0  
..        ...  
663         1  
664         0  
665         1  
666         0  
667         1  

[668 rows x 10 columns]

In [76]:
tr.loc[tr['Age'].isnull(),'Age']=tr.loc[tr['Age'].notnull(),'Age'].median()

In [77]:
tr

Pclass Sex   Age  SibSp  Parch           Ticket     Fare Cabin Embarked  \
0         2   0  29.0      1      0           228414  26.0000   NaN        S   
1         3   1  29.0      0      0         A/5 2466   8.0500   NaN        S   
2         2   1  39.0      0      0           250655  26.0000   NaN        S   
3         3   0  29.0      0      4           349909  21.0750   NaN        S   
4         3   1  25.0      0      0  SOTON/OQ 392076   7.0500   NaN        S   
..      ...  ..   ...    ...    ...              ...      ...   ...      ...   
663       2   0  17.0      0      0       SO/C 14885  10.5000   NaN        S   
664       3   1  29.0      0      0           372622   7.7500   NaN        Q   
665       3   1  32.0      0      0             1601  56.4958   NaN        S   
666       3   0  22.0      0      0             7553   9.8375   NaN        S   
667       3   0  29.0      1      0           367230  15.5000   NaN        Q   

     Survived  
0           1  
1           0  
2           0  
3           0  
4           0  
..        ...  
663         1  
664         0  
665         1  
666         0  
667         1  

[668 rows x 10 columns]

In [78]:
tr.loc[tr['Embarked'].isnull(),'Embarked']='S'

In [79]:
tr

Pclass Sex   Age  SibSp  Parch           Ticket     Fare Cabin Embarked  \
0         2   0  29.0      1      0           228414  26.0000   NaN        S   
1         3   1  29.0      0      0         A/5 2466   8.0500   NaN        S   
2         2   1  39.0      0      0           250655  26.0000   NaN        S   
3         3   0  29.0      0      4           349909  21.0750   NaN        S   
4         3   1  25.0      0      0  SOTON/OQ 392076   7.0500   NaN        S   
..      ...  ..   ...    ...    ...              ...      ...   ...      ...   
663       2   0  17.0      0      0       SO/C 14885  10.5000   NaN        S   
664       3   1  29.0      0      0           372622   7.7500   NaN        Q   
665       3   1  32.0      0      0             1601  56.4958   NaN        S   
666       3   0  22.0      0      0             7553   9.8375   NaN        S   
667       3   0  29.0      1      0           367230  15.5000   NaN        Q   

     Survived  
0           1  
1           0  
2           0  
3           0  
4           0  
..        ...  
663         1  
664         0  
665         1  
666         0  
667         1  

[668 rows x 10 columns]

In [80]:
tr.loc[tr['Embarked']=='S','Embarked']=1

In [81]:
tr.loc[tr['Embarked']=='Q','Embarked']=3
tr.loc[tr['Embarked']=='C','Embarked']=2
tr.loc[tr['Cabin'].isnull(),'Cabin']=0
tr.loc[tr['Cabin']!=0,'Cabin']=1
tr=tr.drop('Ticket',axis=1)

In [82]:
tr

Pclass Sex   Age  SibSp  Parch     Fare Cabin Embarked  Survived
0         2   0  29.0      1      0  26.0000     0        1         1
1         3   1  29.0      0      0   8.0500     0        1         0
2         2   1  39.0      0      0  26.0000     0        1         0
3         3   0  29.0      0      4  21.0750     0        1         0
4         3   1  25.0      0      0   7.0500     0        1         0
..      ...  ..   ...    ...    ...      ...   ...      ...       ...
663       2   0  17.0      0      0  10.5000     0        1         1
664       3   1  29.0      0      0   7.7500     0        3         0
665       3   1  32.0      0      0  56.4958     0        1         1
666       3   0  22.0      0      0   9.8375     0        1         0
667       3   0  29.0      1      0  15.5000     0        3         1

[668 rows x 9 columns]

In [83]:
training_data=tr.values

In [84]:
training_data

array([[2, 0, 29.0, ..., 0, 1, 1],
       [3, 1, 29.0, ..., 0, 1, 0],
       [2, 1, 39.0, ..., 0, 1, 0],
       ...,
       [3, 1, 32.0, ..., 0, 1, 1],
       [3, 0, 22.0, ..., 0, 1, 0],
       [3, 0, 29.0, ..., 0, 3, 1]], dtype=object)

In [85]:
x=training_data[:,:-1]
y=training_data[:,-1]



In [86]:
x

array([[2, 0, 29.0, ..., 26.0, 0, 1],
       [3, 1, 29.0, ..., 8.05, 0, 1],
       [2, 1, 39.0, ..., 26.0, 0, 1],
       ...,
       [3, 1, 32.0, ..., 56.4958, 0, 1],
       [3, 0, 22.0, ..., 9.8375, 0, 1],
       [3, 0, 29.0, ..., 15.5, 0, 3]], dtype=object)

In [87]:
training1=pd.read_csv(r"D:\0000000000002429_training_titanic_x_y_train.csv",delimiter=',')

In [88]:
training1

Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
663       2                             Ilett, Miss. Bertha  female  17.0   
664       3                        Morrow, Mr. Thomas Rowan    male   NaN   
665       3                                   Bing, Mr. Lee    male  32.0   
666       3                     Strandberg, Miss. Ida Sofia  female  22.0   
667       3                  Murphy, Miss. Katherine "Kate"  female   NaN   

     SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0        1      0           228414  26.0000   NaN        S         1  
1        0      0         A/5 2466   8.0500   NaN        S         0  
2        0      0           250655  26.0000   NaN        S         0  
3        0      4           349909  21.0750   NaN        S         0  
4        0      0  SOTON/OQ 392076   7.0500   NaN        S         0  
..     ...    ...              ...      ...   ...      ...       ...  
663      0      0       SO/C 14885  10.5000   NaN        S         1  
664      0      0           372622   7.7500   NaN        Q         0  
665      0      0             1601  56.4958   NaN        S         1  
666      0      0             7553   9.8375   NaN        S         0  
667      1      0           367230  15.5000   NaN        Q         1  

[668 rows x 11 columns]

In [89]:
title_training1=[]
for i in training1['Name']:
    title_training1.append(i.split(',')[1].split('.')[0])

title_training1

[' Mrs',
 ' Mr',
 ' Mr',
 ' Mrs',
 ' Mr',
 ' Mr',
 ' Mrs',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Miss',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Miss',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Miss',
 ' Jonkheer',
 ' Mrs',
 ' Mrs',
 ' Mr',
 ' Mrs',
 ' Miss',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mrs',
 ' Mr',
 ' Mr',
 ' Miss',
 ' Col',
 ' Mr',
 ' Master',
 ' Master',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mrs',
 ' Miss',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mrs',
 ' Mr',
 ' Miss',
 ' Master',
 ' Mr',
 ' Mrs',
 ' Mr',
 ' Miss',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mrs',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mrs',
 ' Miss',
 ' Mrs',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mrs',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Miss',
 ' Miss',
 ' Lady',
 ' Mrs',
 ' Mrs',
 ' Mrs',
 ' Mr',
 ' Mrs',
 ' Mr',
 ' Miss',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mrs',
 ' Mrs',
 ' Miss',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Miss',
 ' Mr',
 ' Mr',
 ' Miss',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Miss',
 ' Mr',
 ' Mr',
 ' Mr',
 ' Miss',
 ' Mr',
 ' Miss',
 ' Mrs',
 ' Mr',
 ' Miss',
 ' Mr',


strip function is used to remove whitespaces from i.
we converted list to nparray because only nparrays can be added to a dataset which we will use in our
training data, also BECAUSE LISTS ARE IMMUTABLE.

All elements appended to the list are characters hence we have to compare each element with '1','0' etc.

An nparray can have elements of 1 datatype ONLY

In [90]:
title_training=[]
for i in training['Name']:
    title_training.append(i.split(',')[1].split('.')[0].strip())
title_training=np.array(title_training)
title_training[title_training=='Master']=0
title_training[title_training=='Miss']=1
title_training[title_training=='Mr']=2
title_training[title_training=='Mrs']=3
title_training[(title_training!='0')&(title_training!='1')&(title_training!='3')&(title_training!='2')]=4
title_training

array(['3', '2', '2', '3', '2', '2', '3', '2', '2', '2', '1', '2', '2',
       '2', '1', '2', '2', '2', '2', '1', '4', '3', '3', '2', '3', '1',
       '2', '2', '2', '2', '3', '2', '2', '1', '4', '2', '0', '0', '2',
       '2', '2', '2', '3', '1', '2', '2', '2', '2', '3', '2', '1', '0',
       '2', '3', '2', '1', '2', '2', '2', '3', '2', '2', '2', '3', '1',
       '3', '2', '2', '2', '2', '3', '2', '2', '2', '2', '1', '1', '4',
       '3', '3', '3', '2', '3', '2', '1', '2', '2', '2', '2', '2', '3',
       '3', '1', '2', '2', '2', '1', '2', '2', '1', '2', '2', '2', '2',
       '1', '2', '2', '2', '1', '2', '1', '3', '2', '1', '2', '2', '2',
       '2', '1', '1', '3', '4', '1', '1', '1', '2', '2', '2', '2', '3',
       '2', '1', '2', '2', '2', '3', '2', '2', '2', '4', '2', '3', '2',
       '2', '2', '2', '3', '2', '1', '1', '3', '2', '3', '1', '3', '2',
       '3', '2', '1', '3', '3', '1', '2', '2', '2', '4', '2', '2', '2',
       '0', '2', '4', '3', '2', '4', '1', '3', '2', '2', '2', '2

In [91]:
title_training=np.array(title_training,dtype='int')

In [92]:
title_training

array([3, 2, 2, 3, 2, 2, 3, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 4, 3,
       3, 2, 3, 1, 2, 2, 2, 2, 3, 2, 2, 1, 4, 2, 0, 0, 2, 2, 2, 2, 3, 1,
       2, 2, 2, 2, 3, 2, 1, 0, 2, 3, 2, 1, 2, 2, 2, 3, 2, 2, 2, 3, 1, 3,
       2, 2, 2, 2, 3, 2, 2, 2, 2, 1, 1, 4, 3, 3, 3, 2, 3, 2, 1, 2, 2, 2,
       2, 2, 3, 3, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2,
       1, 3, 2, 1, 2, 2, 2, 2, 1, 1, 3, 4, 1, 1, 1, 2, 2, 2, 2, 3, 2, 1,
       2, 2, 2, 3, 2, 2, 2, 4, 2, 3, 2, 2, 2, 2, 3, 2, 1, 1, 3, 2, 3, 1,
       3, 2, 3, 2, 1, 3, 3, 1, 2, 2, 2, 4, 2, 2, 2, 0, 2, 4, 3, 2, 4, 1,
       3, 2, 2, 2, 2, 1, 3, 2, 3, 0, 2, 1, 3, 2, 2, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 1, 4, 1, 2, 1, 2, 3, 2, 2, 0, 3, 3, 1, 2, 1, 2, 2, 0, 1, 1,
       1, 2, 3, 2, 2, 2, 3, 2, 3, 2, 2, 0, 3, 2, 2, 2, 2, 3, 2, 1, 2, 2,
       2, 3, 2, 2, 1, 3, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 3, 2, 2, 4,
       2, 2, 3, 2, 2, 2, 0, 0, 2, 3, 1, 2, 2, 0, 2, 2, 2, 3, 1, 2, 2, 1,
       1, 2, 2, 2, 1, 2, 2, 1, 3, 1, 0, 2, 2, 1, 2,

Now we have to convert above 1D array to 2D array and then add it as a seperate column in our training data.

In [93]:
x=np.append(x,title_training.reshape(-1,1),axis=1)
x

array([[2, 0, 29.0, ..., 0, 1, 3],
       [3, 1, 29.0, ..., 0, 1, 2],
       [2, 1, 39.0, ..., 0, 1, 2],
       ...,
       [3, 1, 32.0, ..., 0, 1, 2],
       [3, 0, 22.0, ..., 0, 1, 1],
       [3, 0, 29.0, ..., 0, 3, 1]], dtype=object)

In [94]:
y

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,

In [95]:
x

array([[2, 0, 29.0, ..., 0, 1, 3],
       [3, 1, 29.0, ..., 0, 1, 2],
       [2, 1, 39.0, ..., 0, 1, 2],
       ...,
       [3, 1, 32.0, ..., 0, 1, 2],
       [3, 0, 22.0, ..., 0, 1, 1],
       [3, 0, 29.0, ..., 0, 3, 1]], dtype=object)

In [96]:
y

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,

In [97]:
testing

Pclass                                               Name     Sex   Age  \
0         2                     Davies, Master. John Morgan Jr    male   8.0   
1         1                        Leader, Dr. Alice (Farnham)  female  49.0   
2         3                            Kilgannon, Mr. Thomas J    male   NaN   
3         2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4         1                          McGough, Mr. James Robert    male  36.0   
..      ...                                                ...     ...   ...   
218       3                        Lindqvist, Mr. Eino William    male  20.0   
219       1                  Butt, Major. Archibald Willingham    male  45.0   
220       1  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0   
221       3                   Holm, Mr. John Fredrik Alexander    male  43.0   
222       2           Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5   

     SibSp  Parch             Ticket      Fare Cabin Embarked  
0        1      1         C.A. 33112   36.7500   NaN        S  
1        0      0              17465   25.9292   D17        S  
2        0      0              36865    7.7375   NaN        Q  
3        2      1             243847   27.0000   NaN        S  
4        0      0           PC 17473   26.2875   E25        S  
..     ...    ...                ...       ...   ...      ...  
218      1      0  STON/O 2. 3101285    7.9250   NaN        S  
219      0      0             113050   26.5500   B38        S  
220      1      0           PC 17758  108.9000   C65        C  
221      0      0             C 7075    6.4500   NaN        S  
222      0      2             230080   26.0000    F2        S  

[223 rows x 10 columns]

In [98]:
testing_names=[]
for i in testing['Name']:
    testing_names.append(i.split(',')[1].split('.')[0].strip())
testing_names=np.array(testing_names)
testing_names[testing_names=='Master']='0'
testing_names[testing_names=='Miss']='1'
testing_names[testing_names=='Mr']='2'
testing_names[testing_names=='Mrs']='3'
testing_names[(testing_names!='0')&(testing_names!='1')&(testing_names!='2')&(testing_names!='3')]='4'
testing_names=np.array(testing_names,dtype='int')


In [99]:
testing_names

array([0, 4, 2, 3, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 0, 2, 1, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 1, 2, 4, 2,
       1, 0, 2, 1, 2, 2, 2, 1, 3, 1, 2, 2, 0, 2, 2, 2, 2, 4, 3, 1, 3, 2,
       2, 4, 1, 4, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 0, 1, 1, 2, 1, 0, 1, 1, 4, 4, 2, 2,
       2, 3, 3, 2, 3, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 3, 1, 2, 1, 2,
       1, 2, 2, 1, 2, 0, 2, 1, 3, 1, 1, 2, 2, 2, 3, 1, 3, 1, 1, 2, 1, 2,
       2, 2, 2, 1, 2, 2, 0, 1, 3, 2, 3, 2, 1, 2, 2, 2, 3, 2, 2, 1, 1, 1,
       3, 4, 2, 4, 2, 2, 2, 2, 2, 2, 3, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 4,
       3, 2, 2])

In [100]:
testing=pd.read_csv(r"D:\0000000000002429_test_titanic_x_test.csv",delimiter=',')
testing

Pclass                                               Name     Sex   Age  \
0         2                     Davies, Master. John Morgan Jr    male   8.0   
1         1                        Leader, Dr. Alice (Farnham)  female  49.0   
2         3                            Kilgannon, Mr. Thomas J    male   NaN   
3         2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4         1                          McGough, Mr. James Robert    male  36.0   
..      ...                                                ...     ...   ...   
218       3                        Lindqvist, Mr. Eino William    male  20.0   
219       1                  Butt, Major. Archibald Willingham    male  45.0   
220       1  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0   
221       3                   Holm, Mr. John Fredrik Alexander    male  43.0   
222       2           Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5   

     SibSp  Parch             Ticket      Fare Cabin Embarked  
0        1      1         C.A. 33112   36.7500   NaN        S  
1        0      0              17465   25.9292   D17        S  
2        0      0              36865    7.7375   NaN        Q  
3        2      1             243847   27.0000   NaN        S  
4        0      0           PC 17473   26.2875   E25        S  
..     ...    ...                ...       ...   ...      ...  
218      1      0  STON/O 2. 3101285    7.9250   NaN        S  
219      0      0             113050   26.5500   B38        S  
220      1      0           PC 17758  108.9000   C65        C  
221      0      0             C 7075    6.4500   NaN        S  
222      0      2             230080   26.0000    F2        S  

[223 rows x 10 columns]

axis=1 signifies y axis

In [101]:
testing=testing.drop('Name',axis=1)
testing=testing.drop('Ticket',axis=1)
testing

Pclass     Sex   Age  SibSp  Parch      Fare Cabin Embarked
0         2    male   8.0      1      1   36.7500   NaN        S
1         1  female  49.0      0      0   25.9292   D17        S
2         3    male   NaN      0      0    7.7375   NaN        Q
3         2  female  24.0      2      1   27.0000   NaN        S
4         1    male  36.0      0      0   26.2875   E25        S
..      ...     ...   ...    ...    ...       ...   ...      ...
218       3    male  20.0      1      0    7.9250   NaN        S
219       1    male  45.0      0      0   26.5500   B38        S
220       1  female  17.0      1      0  108.9000   C65        C
221       3    male  43.0      0      0    6.4500   NaN        S
222       2    male  36.5      0      2   26.0000    F2        S

[223 rows x 8 columns]

In [102]:
testing.loc[testing['Sex']=='male','Sex']=1

In [103]:
testing.loc[testing['Sex']=='female','Sex']=0

We have to tell what parameter do we ahve to replace by writing ,'Age'. 
testing.loc[testing['Age'].notnull()] only gets to those rows which have a non null value of testing['Age']

In [104]:
testing.loc[testing['Age'].isnull(),'Age']=testing.loc[testing['Age'].notnull(),'Age'].median()

In [105]:
testing.loc[testing['Cabin'].isnull(),'Cabin']=1
testing.loc[testing['Cabin'].notnull(),'Cabin']=0
testing.loc[testing['Embarked'].isnull(),'Embarked']='S'
testing.loc[testing['Embarked']=='S','Embarked']=1
testing.loc[testing['Embarked']=='C','Embarked']=2
testing.loc[testing['Embarked']=='Q','Embarked']=3


In [106]:
testing

Pclass Sex   Age  SibSp  Parch      Fare Cabin Embarked
0         2   1   8.0      1      1   36.7500     0        1
1         1   0  49.0      0      0   25.9292     0        1
2         3   1  27.0      0      0    7.7375     0        3
3         2   0  24.0      2      1   27.0000     0        1
4         1   1  36.0      0      0   26.2875     0        1
..      ...  ..   ...    ...    ...       ...   ...      ...
218       3   1  20.0      1      0    7.9250     0        1
219       1   1  45.0      0      0   26.5500     0        1
220       1   0  17.0      1      0  108.9000     0        2
221       3   1  43.0      0      0    6.4500     0        1
222       2   1  36.5      0      2   26.0000     0        1

[223 rows x 8 columns]

In [107]:
testing_data=testing.values
testing_data

array([[2, 1, 8.0, ..., 36.75, 0, 1],
       [1, 0, 49.0, ..., 25.9292, 0, 1],
       [3, 1, 27.0, ..., 7.7375, 0, 3],
       ...,
       [1, 0, 17.0, ..., 108.9, 0, 2],
       [3, 1, 43.0, ..., 6.45, 0, 1],
       [2, 1, 36.5, ..., 26.0, 0, 1]], dtype=object)

In [108]:
testing_data=np.append(testing_data,testing_names.reshape(-1,1),axis=1)

In [109]:
testing_data.shape

(223, 9)

In [110]:
training_data.shape

(668, 9)

In [111]:
x.shape

(668, 9)

In [112]:
y.shape

(668,)

In [113]:

from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression(C=2.0)
clf.fit(x,y)

ValueError: Unknown label type: 'unknown'

All values in y are not converted to int type, they must be first converted to int type before LogisticRegression

In [114]:
y=np.array(y,dtype='int')

In [115]:
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression(max_iter=100000, tol=0.0001)
clf.fit(x,y)

LogisticRegression(max_iter=100000)

In [116]:
predicted=clf.predict(testing_data)

In [121]:
np.savetxt(X=predicted,delimiter=',',fname="D:\TitanicPredictions.csv")

See the significance of X=predicted in this!, the above savetext code saves the predictions in
general numberE+number, if we want only 2 decimal places of the number we have to specifiy it using 
fmt='%.0f'

In [124]:
np.savetxt(X=predicted,delimiter=',',fname="D:\TitanicPredictions.csv",fmt='%.0f')